const CARDS_FETCH_REQUEST = "CARDS_FETCH_REQUEST";
const CARDS_FETCH_SUCCESS = "CARDS_FETCH_SUCCESS";
const CARDS_FETCH_FAILURE = "CARDS_FETCH_FAILURE";

const CARD_CREATE = "CARD_CREATE";
const CARD_EDIT = "CARD_EDIT";
const CARD_DELETE = "CARD_DELETE";

const CARD_CREATE_LOCAL = "CARD_CREATE_LOCAL";
const CARD_REMOVE_LOCAL = "CARD_REMOVE_LOCAL";

export const cardConstants = {
	CARDS_FETCH_REQUEST,
	CARDS_FETCH_SUCCESS,
	CARDS_FETCH_FAILURE,
	CARD_CREATE,
	CARD_EDIT,
	CARD_DELETE,
	CARD_CREATE_LOCAL,
	CARD_REMOVE_LOCAL,
};
